[package]
name = "arb"
version = "0.5.1"
authors = ["Adrian Kumpf"]
edition = '2021'

[dependencies]
clap = { version = "3.0.0-beta.5", optional = true }
rusb = "0.9.0"
thiserror = "1.0.30"

[features]
build-binary = ["clap"]

[[bin]]
name = "arb"
required-features = ["build-binary"]
