[package]
name = "arb"
version = "0.5.3"
authors = ["Adrian Kumpf"]
edition = '2021'

[dependencies]
clap = { version = "4.5.1", features = ["derive"], optional = true }
rusb = "0.9.3"
thiserror = "1.0.57"

[features]
build-binary = ["clap"]

[[bin]]
name = "arb"
required-features = ["build-binary"]
