[package]
name = "arb"
version = "0.5.2"
authors = ["Adrian Kumpf"]
edition = '2021'

[dependencies]
clap = { version = "3.1.9", features = ["derive"], optional = true }
rusb = "0.9.1"
thiserror = "1.0.30"

[features]
build-binary = ["clap"]

[[bin]]
name = "arb"
required-features = ["build-binary"]
