[package]
name = "arb"
version = "0.3.0"
authors = ["Adrian Kumpf <adrian.kumpf@posteo.de>"]
edition = '2018'

[dependencies]
structopt = { version = "0.2.13", optional = true }
libusb = { git = "https://github.com/adriankumpf/libusb-rs", branch = "dev" }
lazy_static = "1.2.0"

[features]
build-binary = ["structopt"]

[[bin]]
name = "arb"
required-features = ["build-binary"]
