[package]
name = "arb"
version = "0.1.0"
authors = ["Adrian Kumpf <adrian.kumpf@posteo.de>"]

[dependencies]
libusb = { git = "https://github.com/adriankumpf/libusb-rs", branch = "dev" }
clap = "2.30"
