[package]
name = "arb"
version = "0.2.2"
authors = ["Adrian Kumpf <adrian.kumpf@posteo.de>"]
edition = '2018'

[dependencies]
clap = { version = "2.32.0", optional = true }
libusb = { git = "https://github.com/adriankumpf/libusb-rs", branch = "dev" }

[features]
build-binary = ["clap"]

[[bin]]
name = "arb"
required-features = ["build-binary"]
